### ISSUE TITLE
train images shouldn't be limited to a list

### ISSUE THREAD

**Issue by th3tick** [18xx-maker/schemas#5]
If trains are anything in a directory now, limiting the list to a known set doesn't make sense.  

{
    keyword: 'enum',
    dataPath: '.trains[5].image',
    schemaPath: '#/properties/trains/items/properties/image/enum',
    params: {
      allowedValues: [ '2T', '3T', '4T', '5T', '6T', 'Diesel', 'Pullman' ]
    },
    message: 'should be equal to one of the allowed values'
  }

**Comment by kelsin** [comment]
Good catch.
